# Autogenerated wrapper script for arm_binutils_jll for armv7l-linux-musleabihf
export arm_none_eabi_as, arm_none_eabi_ld, arm_none_eabi_nm, arm_none_eabi_objcopy, arm_none_eabi_objdump, arm_none_eabi_readelf, arm_none_eabi_strip, arm_none_eabihf_as, arm_none_eabihf_ld, arm_none_eabihf_nm, arm_none_eabihf_objcopy, arm_none_eabihf_objdump, arm_none_eabihf_readelf, arm_none_eabihf_strip

JLLWrappers.@generate_wrapper_header("arm_binutils")
JLLWrappers.@declare_executable_product(arm_none_eabi_as)
JLLWrappers.@declare_executable_product(arm_none_eabi_ld)
JLLWrappers.@declare_executable_product(arm_none_eabi_nm)
JLLWrappers.@declare_executable_product(arm_none_eabi_objcopy)
JLLWrappers.@declare_executable_product(arm_none_eabi_objdump)
JLLWrappers.@declare_executable_product(arm_none_eabi_readelf)
JLLWrappers.@declare_executable_product(arm_none_eabi_strip)
JLLWrappers.@declare_executable_product(arm_none_eabihf_as)
JLLWrappers.@declare_executable_product(arm_none_eabihf_ld)
JLLWrappers.@declare_executable_product(arm_none_eabihf_nm)
JLLWrappers.@declare_executable_product(arm_none_eabihf_objcopy)
JLLWrappers.@declare_executable_product(arm_none_eabihf_objdump)
JLLWrappers.@declare_executable_product(arm_none_eabihf_readelf)
JLLWrappers.@declare_executable_product(arm_none_eabihf_strip)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        arm_none_eabi_as,
        "bin/arm-none-eabi-as",
    )

    JLLWrappers.@init_executable_product(
        arm_none_eabi_ld,
        "bin/arm-none-eabi-ld",
    )

    JLLWrappers.@init_executable_product(
        arm_none_eabi_nm,
        "bin/arm-none-eabi-nm",
    )

    JLLWrappers.@init_executable_product(
        arm_none_eabi_objcopy,
        "bin/arm-none-eabi-objcopy",
    )

    JLLWrappers.@init_executable_product(
        arm_none_eabi_objdump,
        "bin/arm-none-eabi-objdump",
    )

    JLLWrappers.@init_executable_product(
        arm_none_eabi_readelf,
        "bin/arm-none-eabi-readelf",
    )

    JLLWrappers.@init_executable_product(
        arm_none_eabi_strip,
        "bin/arm-none-eabi-strip",
    )

    JLLWrappers.@init_executable_product(
        arm_none_eabihf_as,
        "bin/arm-none-eabihf-as",
    )

    JLLWrappers.@init_executable_product(
        arm_none_eabihf_ld,
        "bin/arm-none-eabihf-ld",
    )

    JLLWrappers.@init_executable_product(
        arm_none_eabihf_nm,
        "bin/arm-none-eabihf-nm",
    )

    JLLWrappers.@init_executable_product(
        arm_none_eabihf_objcopy,
        "bin/arm-none-eabihf-objcopy",
    )

    JLLWrappers.@init_executable_product(
        arm_none_eabihf_objdump,
        "bin/arm-none-eabihf-objdump",
    )

    JLLWrappers.@init_executable_product(
        arm_none_eabihf_readelf,
        "bin/arm-none-eabihf-readelf",
    )

    JLLWrappers.@init_executable_product(
        arm_none_eabihf_strip,
        "bin/arm-none-eabihf-strip",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
